name: CI-Pretrain

on:
  release:
    types:
      - created  

defaults:
  run:
    shell: bash

jobs:
  pretrain:
    name: Pretrain
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - run: TEST_TRANSFORMERS_PRETRAIN=yes julia --project -e 'using Pkg; Pkg.instantiate(); Pkg.build(); Pkg.test(; coverage=true)';
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
